---
quditto_version: 2.0
config:
  application_interface: etsi-gs-qkd-014
  qkd_protocol: bb84
  controller: A
  ip_controller: 172.20.35.105
  netsquid_user: pblanco1clab
  netsquid_pwd: gvPBDaGhxVA9TX

sites:
  - Sevilla
  - Malaga
  - Cadiz

nodes:
  - node_name: A
    node_site: Sevilla
    node_ip: 172.20.35.105
    neighbour_nodes:

      - name: B
        link_length: 154
        protocol: bb84_att.py
        eavesdropper: False

      - name: C
        link_length: 100
        protocol: bb84_with_eve.py
        eavesdropper: True
        eavesdropper_parameters:
          eavesdropper_distance: 45
          percentage_intercepted_qubits: 10

  - node_name: B
    node_site: Malaga
    node_ip: 172.20.44.165
    neighbour_nodes:

      - name: A
        link_length: 154
        protocol: bb84_att.py
        eavesdropper: False

  - node_name: C
    node_site: Cadiz
    node_ip: 172.20.34.83
    neighbour_nodes:

    - name: A
      link_length: 100
      protocol: bb84_with_eve.py
      eavesdropper: True
      eavesdropper_parameters:
        eavesdropper_distance: 55
        percentage_intercepted_qubits: 10

